### ISSUE TITLE
[ioctl] bc delegate command to accept operation address

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3900]
### Description of new feature request
an `ioctl bc delegate` command is newly added, like below
```
ioctl bc delegate cpc --endpoint=api.iotex.one:443
{
	name: cpc
	ownerAddress: io1smh0a4ms9fc5p8v9h9l7ffgkekv032hzsdkr9a
	operatorAddress: io16fknjsnhj6m5x2fawu5tqfrk6pr9r9xyz489vk
	rewardAddress: io12mgttmfa2ffn9uqvn0yn37f4nz43d248l2ga85
	totalWeightedVotes: 68963450.120222472655746524
	selfStakeBucketIdx: 12
	selfStakingTokens: 2975349.881825114451272576 IOTX
}
```
make this command to also accept the operator address as input, that is 
```
ioctl bc delegate io16fknjsnhj6m5x2fawu5tqfrk6pr9r9xyz489vk --endpoint=api.iotex.one:443
```
will output the same result

### Is this a hard-fork (and height to be activated)
- [] Yes
- Name of activation height:

### Implementation plan
- [] Phase 1 description (PR number)
- [] Phase 2 description (PR number)
- [] Phase 3 description (PR number)

### Affected modules
- [] action
- [] actpool
- [] api
- [] blockchain
- [] blockindex
- [] blocksync
- [] chainservice
- [] config
- [] consensus
- [] db
- [] dispatcher
- [x] ioctl
- [] p2p
- [] server
- [] state
- [] tools

**Comment by dustinxie** [comment]
refer to https://github.com/iotexproject/iotex-core/pull/3891
