### ISSUE TITLE
[api] web3 debug_traceCall support custom javascript tracing

### ISSUE THREAD

**Issue by millken** [iotexproject/iotex-core#3930]
https://geth.ethereum.org/docs/developers/evm-tracing/custom-tracer

### Is this a hard-fork (and height to be activated)
- [] Yes
- Name of activation height:

### Implementation plan
- [] Phase 1 description (PR number)
- [] Phase 2 description (PR number)
- [] Phase 3 description (PR number)

### Affected modules
- [] action
- [] actpool
- [x] api
- [] blockchain
- [] blockindex
- [] blocksync
- [] chainservice
- [] config
- [] consensus
- [] db
- [] dispatcher
- [] ioctl
- [] p2p
- [] server
- [] state
- [] tools

**Comment by ququzone** [comment]
Example for Ethereum:

```bash
curl --request POST \
     --url https://nd-422-757-666.p2pify.com/0a9d79d93fb2f4a4b1e04695da2b77a7/ \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "debug_traceCall",
  "params": [
    {
      "from": "0x1f9090aaE28b8a3dCeaDf281B0F12828e676c326",
      "to": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      "gas": "0x1E9EF",
      "gasPrice": "0xBD32B2ABC",
      "value": "0x1251"
    },
    "latest",
    {
      "tracer": "{data: [], fault: function(log) {}, step: function(log) { this.data.push({'op':log.op.toString(), 'gas':log.getGas()}); }, result: function() { return this.data; }}"
    }
  ]
}
'
```
