### ISSUE TITLE
ioctl enable IIP-13

### ISSUE THREAD

**Issue by envestcc** [iotexproject/iotex-core#3945]
### Is this a hard-fork (and height to be activated)
- [] Yes
- Name of activation height:

### Implementation plan
- [x] Phase 1 description (PR number)
   i think add `ioctl nft bucket info 123` command to query nft bucket 123
   `ioctl nft bucket stake/transfer/unstake/xxx` to operate nft bucket
- [x] Phase 2 description (PR number)
   add `ioctl nft bucketlist voter/cand` command to query nft bucket by voter or candidates
- [x] Phase 3 description (PR number)
   in the future, add `ioctl nft xxx` command for more nft actions, like query an nft by contract name/address and id

### Affected modules
- [] action
- [] actpool
- [] api
- [] blockchain
- [] blockindex
- [] blocksync
- [] chainservice
- [] config
- [] consensus
- [] db
- [] dispatcher
- [] ioctl
- [] p2p
- [] server
- [] state
- [] tools
