### ISSUE TITLE
web3 RPC to support BlockReward type transaction

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#4046]
### Description of new feature request
for integration with https://chainspect.app/dashboard/tps. They want to eliminate any non-user transaction from a block to accurately calculate the real TPS of a blockchain. So they want to identify any protocol-initiated tx

We can convert the BlockReward tx, with `ContractAddress` field in the receipt equals to the protocol address `0xA576C141e5659137ddDa4223d209d4744b2106BE`. This would allow the receiving client to uniquely identify the BlockReward tx

### Is this a hard-fork (and height to be activated)
- [] Yes
- Name of activation height:

### Implementation plan
- [] Phase 1 description (PR number)
- [] Phase 2 description (PR number)
- [] Phase 3 description (PR number)

### Affected modules
- [x] action
- [] actpool
- [x] api
- [] blockchain
- [] blockindex
- [] blocksync
- [] chainservice
- [] config
- [] consensus
- [] db
- [] dispatcher
- [] ioctl
- [] p2p
- [] server
- [] state
- [] tools
